""""""""""""""" Vundle
set nocompatible
filetype off

set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

Bundle 'gmarik/Vundle.vim'
Bundle 'altercation/vim-colors-solarize'

Bundle 'Valloric/YouCompleteMe'
Bundle 'Valloric/ListToggle'

""" 语法检查
Bundle 'scrooloose/syntastic'

Bundle 'fatih/vim-go'
Bundle 'nvie/vim-flake'
Bundle 'majutsushi/tagbar'
Bundle 'ctrlpvim/ctrlp.vim'
Bundle 'scrooloose/nerdtree'
Bundle 'mileszs/ack.vim'
Bundle 'davidhalter/jedi-vim'

" 此行配置没什么鸟用，在~/.vim/bundle/minibufexpl.vim/plugin中下载minibufexpl.vim文件即可
" 缓存配置
Bundle 'fholgado/minibufexpl.vim'

call vundle#end()

filetype plugin indent on

syntax on
set nu
set nobackup
set background=dark
if has('gui_running')
	set background=light
else
	set background=dark
endif


"" ycm设置
let g:ycm_global_ycm_extra_conf = '~/.vim/bundle/YouCompleteMe/third_party/ycmd/cpp/ycm/.ycm_extra_conf.py'
let g:ycm_confirm_extra_conf=0
map gg :YcmCompleter GoToDefinitionElseDeclaration

let g:tagbar_ctags_bin='ctags'
let g:tagbar_width=40
let g:Tlist_Ctags_Cmd='/usr/local/Cellar/ctags/5.8_1/bin/ctags'
map <F2> :GoImports<CR>
map <F3> :Tagbar<CR>
map <F5> :GoImplements<CR>
map gj :GoDef<CR>
map <F6> :NERDTree<CR>

" miniBufExpl
"minibufexplorer窗口最大高度为1行
let g:miniBufExplMaxSize = 2
" buffer 切换快捷键
map m :MBEbn<cr>
map , :MBEbp<cr>

set ts=4
set expandtab
set hlsearch
set ic
set laststatus=2

""" 设置折叠
set foldmethod=indent
nnoremap gh za
set foldlevelstart=99

" 设置文件为unix系统格式
set fileformat=unix
" 设置文件解码方式，以下任意一种方式匹配则使用该方式解码
set fileencodings=utf-8,gb18030,gbk,gb2312,big5
" 设置终端显示编码和实际编码一致
let &termencoding=&encoding
